# Generated by Django 2.0.7 on 2018-07-29 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='animal',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='avatar',
            name='desc',
            field=models.CharField(default='', max_length=255),
        ),
    ]
